test: 署名の検証

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -124,8 +124,6 @@ jobs:
           APPLE_API_KEY: ${{ env.APPLE_API_KEY_PATH }}
           APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
           APPLE_API_ISSUER: ${{ secrets.APPLE_API_ISSUER }}
-
-          DEBUG: electron-osx-sign*
         run: npm run build:${{ matrix.platform }}
 
       - name: Get version from package.json
@@ -136,12 +134,12 @@ jobs:
         if: startsWith(matrix.os,'macos')
         run: codesign --verify --deep --strict dist/minr-desktop-*.dmg || echo "DMG signing failed."
 
-      - name: Verify App Signing Inside DMG
-        if: startsWith(matrix.os,'macos')
-        run: |
-          hdiutil attach dist/minr-desktop-*.dmg
-          codesign --verify --deep --strict "/Volumes/minr-desktop ${{ env.PACKAGE_VERSION }}-${{ matrix.arch }}/minr-desktop.app" || echo "App signing inside DMG failed."
-          hdiutil detach /Volumes/minr-desktop
+      # - name: Verify App Signing Inside DMG
+      #   if: startsWith(matrix.os,'macos')
+      #   run: |
+      #     hdiutil attach dist/minr-desktop-*.dmg
+      #     codesign --verify --deep --strict "/Volumes/minr-desktop ${{ env.PACKAGE_VERSION }}-${{ matrix.arch }}/minr-desktop.app" || echo "App signing inside DMG failed."
+      #     hdiutil detach /Volumes/minr-desktop
 
       - name: Verify Notarization
         if: startsWith(matrix.os,'macos')
